image: python:3.6

all_tests:
  script:
   # this configures Django application to use attached postgres database that is run on `postgres` host
   - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
   - apt-get update -qy
   - apt-get install -y python-dev python-pip
   - pip install -r requirements/test.txt
   - python manage.py test --settings=conf.settings.test
   - python3 manage.py test -k --settings=conf.settings.test
  when: on_success
  only:
    - dev
