[GLOBAL]

[LOCAL]
DEBUG = True
ALLOWED_HOSTS = localhost, 127.0.0.1, [::1]

; SECRET KEY GENERATOR: KEEP THIS VALUE SECRET.
; http://www.miniwebtool.com/django-secret-key-generator/
SECRET_KEY = t1)8r%4r!c2-4k-)#zjy(q6qo1b_cz5o05xxj2-oa96fph&i10

; SQLite3
DATABASE_ENGINE = django.db.backends.sqlite3
DATABASE_NAME = db.sqlite3
DATABASE_USER =
DATABASE_PASSWORD =
DATABASE_HOST =
DATABASE_PORT =

; PostgreSQL
;DATABASE_ENGINE = django.db.backends.postgresql
;DATABASE_NAME = spam
;DATABASE_USER = ham
;DATABASE_PASSWORD = eggs
;DATABASE_HOST = 127.0.0.1
;DATABASE_PORT = 5432
